/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mobius
 * OpenAPI spec version: 0.1.0
 */
/**
 * Activity is an entry of the activity feed of a Workstream.
 */
export interface Activity {
  /** Actor is the GitHub login that did the activity */
  actor: string;
  /** ID increases with each new activity */
  id: number;
  /** Issue is the number of the issue of the activity */
  issue: number;
  /** Link is the GitHub URL of the activity */
  link: string;
  /** Repository is the repository of the Workstream issue, as "owner/name" */
  repository: string;
  /** Text tells what happened */
  text: string;
  /** Time is the time of the activity */
  time: string;
  /** Workstream is the number of the Workstream issue */
  workstream: number;
}

/**
 * Additional error details
 */
export type ErrorResponseDetails = {[key: string]: unknown};

/**
 * Generic error response structure
 */
export interface ErrorResponse {
  /** Additional error details */
  details?: ErrorResponseDetails;
  /** Error message */
  error: string;
}

/**
 * Health is the state of the server.
 */
export interface Health {
  /** Status is "ok" when the server can serve requests */
  status: string;
  /** Time is the current time of the server */
  time: string;
}

/**
 * LiveEvents are the events of the live event stream.
 */
export type LiveEvents = {
  data: Activity;
  event: 'activity';
  id?: string;
};

/**
 * Field-level validation errors (maps field names to arrays of error messages)
 */
export type ValidationErrorResponseDetails = {[key: string]: string[]};

/**
 * Validation error response with field-level details
 */
export interface ValidationErrorResponse {
  /** Field-level validation errors (maps field names to arrays of error messages) */
  details?: ValidationErrorResponseDetails;
  /** Error message */
  error: string;
}

/**
 * Workstream is a Workstream that has rows in the database.
 */
export interface Workstream {
  /** LastActivity is the time of the latest row of the Workstream */
  lastActivity: string;
  /** Number is the number of the Workstream issue */
  number: number;
  /** OpenTasks is the number of tasks that are not ended or stopped */
  openTasks: number;
  /** Repository is the repository of the Workstream issue, as "owner/name" */
  repository: string;
  /** Tasks is the number of tasks of the Workstream */
  tasks: number;
}

/**
 * Bad Request - Validation failed
 */
export type BadRequestResponse = ValidationErrorResponse;

/**
 * Internal Server Error
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Unprocessable Entity - Request body could not be parsed
 */
export type UnprocessableEntityResponse = ErrorResponse;

export type getHealthResponse200 = {
  data: Health
  status: 200
}

export type getHealthResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getHealthResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type getHealthResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
export type getHealthResponseError = (getHealthResponse400 | getHealthResponse422 | getHealthResponse500) & {
  headers: Headers;
};

export type getHealthResponse = (getHealthResponseSuccess | getHealthResponseError)

export const getGetHealthUrl = () => {




  return `/api/health`
}

/**
 * GetHealth returns the state of the server.
 */
export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  const res = await fetch(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthResponse
}



export type listWorkstreamsResponse200 = {
  data: Workstream[]
  status: 200
}

export type listWorkstreamsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listWorkstreamsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type listWorkstreamsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWorkstreamsResponseSuccess = (listWorkstreamsResponse200) & {
  headers: Headers;
};
export type listWorkstreamsResponseError = (listWorkstreamsResponse400 | listWorkstreamsResponse422 | listWorkstreamsResponse500) & {
  headers: Headers;
};

export type listWorkstreamsResponse = (listWorkstreamsResponseSuccess | listWorkstreamsResponseError)

export const getListWorkstreamsUrl = () => {




  return `/api/workstreams`
}

/**
 * ListWorkstreams returns the Workstreams of the database, the most recently active first.
 */
export const listWorkstreams = async ( options?: RequestInit): Promise<listWorkstreamsResponse> => {

  const res = await fetch(getListWorkstreamsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listWorkstreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listWorkstreamsResponse
}
