/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mobius
 * OpenAPI spec version: 0.1.0
 */
/**
 * Activity is an entry of the activity feed of a Workstream.
 */
export interface Activity {
  /** Actor is the GitHub login that did the activity */
  actor: string;
  /** ID increases with each new activity */
  id: number;
  /** Issue is the number of the issue of the activity */
  issue: number;
  /** Link is the GitHub URL of the activity */
  link: string;
  /** Repository is the repository of the Workstream issue, as "owner/name" */
  repository: string;
  /** Text tells what happened */
  text: string;
  /** Time is the time of the activity */
  time: string;
  /** Workstream is the number of the Workstream issue */
  workstream: number;
}

/**
 * DeviceLogin is the login of a device with the access password.
 */
export interface DeviceLogin {
  /** CreatedAt is the time of the login */
  createdAt: string;
  /** ID is the id of the device login */
  id: number;
  /** UserAgent names the browser of the device */
  userAgent: string;
}

/**
 * Devices are the device logins.
 */
export interface Devices {
  /** Logins are the device logins, the newest first */
  logins: DeviceLogin[];
  /** ThisDevice is the id of the device login of the request */
  thisDevice: number;
}

/**
 * Workstream is a Workstream that has rows in the database.
 */
export interface Workstream {
  /** LastActivity is the time of the latest row of the Workstream */
  lastActivity: string;
  /** Number is the number of the Workstream issue */
  number: number;
  /** OpenTasks is the number of tasks that are not ended or stopped */
  openTasks: number;
  /** Repository is the repository of the Workstream issue, as "owner/name" */
  repository: string;
  /** Tasks is the number of tasks of the Workstream */
  tasks: number;
}

export interface EnvelopeArrayWorkstream {
  /** Data is the payload of the response */
  data: Workstream[];
}

export interface EnvelopeDevices {
  /** Data is the payload of the response */
  data: Devices;
}

/**
 * Health is the state of the server.
 */
export interface Health {
  /** Status is "ok" when the server can serve requests */
  status: string;
  /** Time is the current time of the server */
  time: string;
}

export interface EnvelopeHealth {
  /** Data is the payload of the response */
  data: Health;
}

/**
 * Additional error details
 */
export type ErrorResponseDetails = {[key: string]: unknown};

/**
 * Generic error response structure
 */
export interface ErrorResponse {
  /** Additional error details */
  details?: ErrorResponseDetails;
  /** Error message */
  error: string;
}

/**
 * LiveEvents are the events of the live event stream.
 */
export type LiveEvents = {
  data: Activity;
  event: 'activity';
  id?: string;
};

export interface LoginBody {
  /** Password is the access password */
  password: string;
}

/**
 * Field-level validation errors (maps field names to arrays of error messages)
 */
export type ValidationErrorResponseDetails = {[key: string]: string[]};

/**
 * Validation error response with field-level details
 */
export interface ValidationErrorResponse {
  /** Field-level validation errors (maps field names to arrays of error messages) */
  details?: ValidationErrorResponseDetails;
  /** Error message */
  error: string;
}

/**
 * Bad Request - Validation failed
 */
export type BadRequestResponse = ValidationErrorResponse;

/**
 * Internal Server Error
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Unprocessable Entity - Request body could not be parsed
 */
export type UnprocessableEntityResponse = ErrorResponse;

export type listDevicesResponse200 = {
  data: EnvelopeDevices
  status: 200
}

export type listDevicesResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listDevicesResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type listDevicesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listDevicesResponseSuccess = (listDevicesResponse200) & {
  headers: Headers;
};
export type listDevicesResponseError = (listDevicesResponse400 | listDevicesResponse422 | listDevicesResponse500) & {
  headers: Headers;
};

export type listDevicesResponse = (listDevicesResponseSuccess | listDevicesResponseError)

export const getListDevicesUrl = () => {




  return `/api/devices`
}

/**
 * ListDevices returns the device logins.
 */
export const listDevices = async ( ): Promise<listDevicesResponse> => {

  const res = await fetch(getListDevicesUrl(),
  {

    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDevicesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDevicesResponse
}



export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type logoutResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type logoutResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponse400 | logoutResponse422 | logoutResponse500) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = (id: number,) => {




  return `/api/devices/${id}`
}

/**
 * Logout deletes a device login.
 */
export const logout = async (id: number, ): Promise<logoutResponse> => {

  const res = await fetch(getLogoutUrl(id),
  {

    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as logoutResponse
}



export type getHealthResponse200 = {
  data: EnvelopeHealth
  status: 200
}

export type getHealthResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getHealthResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type getHealthResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
export type getHealthResponseError = (getHealthResponse400 | getHealthResponse422 | getHealthResponse500) & {
  headers: Headers;
};

export type getHealthResponse = (getHealthResponseSuccess | getHealthResponseError)

export const getGetHealthUrl = () => {




  return `/api/health`
}

/**
 * GetHealth returns the state of the server.
 */
export const getHealth = async ( ): Promise<getHealthResponse> => {

  const res = await fetch(getGetHealthUrl(),
  {

    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthResponse
}



export type loginResponse204 = {
  data: void
  status: 204
}

export type loginResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type loginResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type loginResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type loginResponseSuccess = (loginResponse204) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse422 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/login`
}

/**
 * Login makes a device login when the password is the access password, and sets the token of the device login in a cookie.
 */
export const login = async (loginBody: LoginBody, ): Promise<loginResponse> => {

  const res = await fetch(getLoginUrl(),
  {

    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(loginBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type listWorkstreamsResponse200 = {
  data: EnvelopeArrayWorkstream
  status: 200
}

export type listWorkstreamsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listWorkstreamsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type listWorkstreamsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listWorkstreamsResponseSuccess = (listWorkstreamsResponse200) & {
  headers: Headers;
};
export type listWorkstreamsResponseError = (listWorkstreamsResponse400 | listWorkstreamsResponse422 | listWorkstreamsResponse500) & {
  headers: Headers;
};

export type listWorkstreamsResponse = (listWorkstreamsResponseSuccess | listWorkstreamsResponseError)

export const getListWorkstreamsUrl = () => {




  return `/api/workstreams`
}

/**
 * ListWorkstreams returns the Workstreams of the database, the most recently active first.
 */
export const listWorkstreams = async ( ): Promise<listWorkstreamsResponse> => {

  const res = await fetch(getListWorkstreamsUrl(),
  {

    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listWorkstreamsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listWorkstreamsResponse
}
