/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GetHealth returns the state of the server. */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description Generic error response structure
         */
        ErrorResponse: {
            /** @description Additional error details */
            details?: Record<string, never>;
            /** @description Error message */
            error: string;
        };
        /**
         * Health
         * @description Health is the state of the server.
         */
        Health: {
            /** @description Status is "ok" when the server can serve requests */
            status: string;
            /**
             * Format: date-time
             * @description Time is the current time of the server
             */
            time: string;
        };
        /**
         * ValidationErrorResponse
         * @description Validation error response with field-level details
         */
        ValidationErrorResponse: {
            /** @description Field-level validation errors (maps field names to arrays of error messages) */
            details?: Record<string, never>;
            /** @description Error message */
            error: string;
        };
    };
    responses: {
        /** @description Bad Request - Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unprocessable Entity - Request body could not be parsed */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
