/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description StreamEvents sends the latest activities, and then each new activity. When the request has Last-Event-ID, it sends the activities after that id in place of the latest activities. */
        get: operations["StreamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GetHealth returns the state of the server. */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ListWorkstreams returns the Workstreams of the database, the most recently active first. */
        get: operations["ListWorkstreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @description Activity is an entry of the activity feed of a Workstream.
         */
        Activity: {
            /** @description Actor is the GitHub login that did the activity */
            actor: string;
            /** @description ID increases with each new activity */
            id: number;
            /** @description Issue is the number of the issue of the activity */
            issue: number;
            /** @description Link is the GitHub URL of the activity */
            link: string;
            /** @description Repository is the repository of the Workstream issue, as "owner/name" */
            repository: string;
            /** @description Text tells what happened */
            text: string;
            /**
             * Format: date-time
             * @description Time is the time of the activity
             */
            time: string;
            /** @description Workstream is the number of the Workstream issue */
            workstream: number;
        };
        /**
         * ErrorResponse
         * @description Generic error response structure
         */
        ErrorResponse: {
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
            /** @description Error message */
            error: string;
        };
        /**
         * Health
         * @description Health is the state of the server.
         */
        Health: {
            /** @description Status is "ok" when the server can serve requests */
            status: string;
            /**
             * Format: date-time
             * @description Time is the current time of the server
             */
            time: string;
        };
        /**
         * LiveEvents
         * @description LiveEvents are the events of the live event stream.
         */
        LiveEvents: {
            data: string;
            /** @constant */
            event: "activity";
            id?: string;
        };
        /**
         * ValidationErrorResponse
         * @description Validation error response with field-level details
         */
        ValidationErrorResponse: {
            /** @description Field-level validation errors (maps field names to arrays of error messages) */
            details?: {
                [key: string]: string[];
            };
            /** @description Error message */
            error: string;
        };
        /**
         * Workstream
         * @description Workstream is a Workstream that has rows in the database.
         */
        Workstream: {
            /**
             * Format: date-time
             * @description LastActivity is the time of the latest row of the Workstream
             */
            lastActivity: string;
            /** @description Number is the number of the Workstream issue */
            number: number;
            /** @description OpenTasks is the number of tasks that are not ended or stopped */
            openTasks: number;
            /** @description Repository is the repository of the Workstream issue, as "owner/name" */
            repository: string;
            /** @description Tasks is the number of tasks of the Workstream */
            tasks: number;
        };
    };
    responses: {
        /** @description Bad Request - Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unprocessable Entity - Request body could not be parsed */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StreamEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description LastEventID is the id of the last activity that the client got */
                "Last-Event-ID"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListWorkstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workstream"][];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
