[package]
name = "mobius-engine"
version.workspace = true
edition.workspace = true

[dependencies]
getrandom = { workspace = true }
humantime-serde = { workspace = true }
mobius-domain = { workspace = true }
mobius-github = { workspace = true }
mobius-runner = { workspace = true }
mobius-store = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
time = { workspace = true, features = ["formatting", "macros"] }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
toml = { workspace = true }
