[package]
name = "mobius-ui"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
mobius-api = { workspace = true }
mobius-domain = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting", "macros"] }

[features]
web = ["dioxus/web"]
server = ["mobius-api/server"]
