// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Event struct {
	ID         int64
	Time       string
	Repository string
	Workstream int64
	Issue      int64
	Actor      string
	Text       string
	Link       string
}
