// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Event struct {
	ID         int64
	Time       string
	Repository string
	Workstream int64
	Issue      int64
	Actor      string
	Text       string
	Link       string
}

type GithubApp struct {
	AppID              int64
	Slug               string
	PrivateKey         string
	ClientID           string
	ClientSecret       string
	UserToken          sql.NullString
	RefreshToken       sql.NullString
	UserTokenExpiresAt sql.NullString
}
