// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type ChatMessage struct {
	ID           int64
	Repository   string
	Workstream   int64
	Author       string
	Time         string
	Text         string
	Organization string
	BrowserID    sql.NullString
	DeliveredAt  sql.NullString
}

type Event struct {
	ID         int64
	Time       string
	Repository string
	Workstream int64
	Issue      int64
	Actor      string
	Text       string
	Link       string
}

type FullSlot struct {
	ID     int64
	Since  string
	ItemAt sql.NullString
}

type GithubApp struct {
	AppID              int64
	Slug               string
	PrivateKey         string
	ClientID           string
	ClientSecret       string
	UserToken          sql.NullString
	RefreshToken       sql.NullString
	UserTokenExpiresAt sql.NullString
}

type HarnessPause struct {
	Harness     string
	PausedUntil string
	InboxItem   int64
}

type InboxItem struct {
	ID           int64
	Kind         string
	Repository   string
	Workstream   int64
	Issue        int64
	Text         string
	Link         string
	Time         string
	DismissedAt  sql.NullString
	Organization string
}

type LeadEvent struct {
	ID          int64
	Repository  string
	Workstream  int64
	Kind        string
	Payload     string
	Time        string
	DeliveredAt sql.NullString
	ChatMessage sql.NullInt64
	Issue       sql.NullInt64
	Held        int64
	Comment     sql.NullInt64
	Review      sql.NullBool
}

type Session struct {
	ID           int64
	Role         string
	Harness      string
	Model        string
	Repository   string
	Workstream   int64
	AcpSessionID sql.NullString
	StartedAt    string
	EndedAt      sql.NullString
	EndReason    sql.NullString
	QueueReason  sql.NullString
	Organization string
	Issue        sql.NullInt64
	Parent       sql.NullInt64
	Effort       sql.NullString
}

type Task struct {
	ID             int64
	Repository     string
	Issue          int64
	Workstream     int64
	State          string
	DispatchedAt   string
	Branch         sql.NullString
	QueuedAt       sql.NullString
	FixRounds      int64
	PullRequest    sql.NullInt64
	JudgedAt       sql.NullString
	WorkerRestarts int64
	Worker         sql.NullString
	WorkerInput    sql.NullString
	ReviewRounds   int64
	ReviewComment  sql.NullInt64
	CheckHead      sql.NullString
	ApprovedReview sql.NullString
	RefusedReview  sql.NullString
	NeedsHumanAt   sql.NullString
	ConflictHead   sql.NullString
	CiFailedHead   sql.NullString
	StateAt        string
	LongWaitAt     sql.NullString
	CheckErrors    int64
}

type Transcript struct {
	ID      int64
	Session int64
	Time    string
	Kind    string
	Json    string
}

type TurnUsage struct {
	ID               int64
	Session          int64
	Task             sql.NullInt64
	Issue            sql.NullInt64
	Workstream       int64
	Organization     string
	Repository       string
	Role             string
	Harness          string
	Model            string
	ReportedModel    sql.NullString
	Effort           sql.NullString
	StartedAt        string
	EndedAt          string
	InputTokens      sql.NullInt64
	OutputTokens     sql.NullInt64
	CacheReadTokens  sql.NullInt64
	CacheWriteTokens sql.NullInt64
	CostUsd          sql.NullFloat64
}
