// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events WHERE id > ? ORDER BY id
`

func (q *Queries) ListEventsAfter(ctx context.Context, id int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestEvents = `-- name: ListLatestEvents :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListLatestEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listLatestEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkstreams = `-- name: ListWorkstreams :many
WITH activity AS (
    SELECT repository, workstream, dispatched_at AS time FROM tasks
    UNION ALL
    SELECT repository, workstream, started_at FROM sessions
    UNION ALL
    SELECT repository, workstream, time FROM chat_messages
    UNION ALL
    SELECT repository, workstream, time FROM lead_events
    UNION ALL
    SELECT repository, workstream, time FROM events
    UNION ALL
    SELECT repository, workstream, time FROM inbox_items
)
SELECT
    activity.repository,
    activity.workstream,
    CAST(MAX(activity.time) AS TEXT) AS last_activity,
    (SELECT COUNT(*) FROM tasks
     WHERE tasks.repository = activity.repository AND tasks.workstream = activity.workstream) AS tasks,
    (SELECT COUNT(*) FROM tasks
     WHERE tasks.repository = activity.repository AND tasks.workstream = activity.workstream
       AND tasks.state NOT IN ('ended', 'stopped')) AS open_tasks
FROM activity
WHERE activity.repository != '' AND activity.workstream != 0
GROUP BY activity.repository, activity.workstream
ORDER BY last_activity DESC
`

type ListWorkstreamsRow struct {
	Repository   string
	Workstream   int64
	LastActivity string
	Tasks        int64
	OpenTasks    int64
}

func (q *Queries) ListWorkstreams(ctx context.Context) ([]ListWorkstreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkstreamsRow
	for rows.Next() {
		var i ListWorkstreamsRow
		if err := rows.Scan(
			&i.Repository,
			&i.Workstream,
			&i.LastActivity,
			&i.Tasks,
			&i.OpenTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
