// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addDeviceLogin = `-- name: AddDeviceLogin :exec
INSERT INTO device_logins (token_hash, password_fingerprint, user_agent, created_at)
VALUES (?, ?, ?, ?)
`

type AddDeviceLoginParams struct {
	TokenHash           []byte
	PasswordFingerprint []byte
	UserAgent           string
	CreatedAt           string
}

func (q *Queries) AddDeviceLogin(ctx context.Context, arg AddDeviceLoginParams) error {
	_, err := q.db.ExecContext(ctx, addDeviceLogin,
		arg.TokenHash,
		arg.PasswordFingerprint,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const addGitHubApp = `-- name: AddGitHubApp :exec
INSERT INTO github_apps (app_id, slug, private_key, client_id, client_secret)
VALUES (?, ?, ?, ?, ?)
`

type AddGitHubAppParams struct {
	AppID        int64
	Slug         string
	PrivateKey   string
	ClientID     string
	ClientSecret string
}

func (q *Queries) AddGitHubApp(ctx context.Context, arg AddGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, addGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.PrivateKey,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const deleteDeviceLogin = `-- name: DeleteDeviceLogin :exec
DELETE FROM device_logins WHERE id = ?
`

func (q *Queries) DeleteDeviceLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceLogin, id)
	return err
}

const deleteOtherPasswordLogins = `-- name: DeleteOtherPasswordLogins :exec
DELETE FROM device_logins WHERE password_fingerprint != ?
`

func (q *Queries) DeleteOtherPasswordLogins(ctx context.Context, passwordFingerprint []byte) error {
	_, err := q.db.ExecContext(ctx, deleteOtherPasswordLogins, passwordFingerprint)
	return err
}

const findDeviceLogin = `-- name: FindDeviceLogin :one
SELECT id FROM device_logins WHERE token_hash = ?
`

func (q *Queries) FindDeviceLogin(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, findDeviceLogin, tokenHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT app_id, slug, private_key, client_id, client_secret, user_token, refresh_token, user_token_expires_at FROM github_apps WHERE app_id = ?
`

func (q *Queries) GetGitHubApp(ctx context.Context, appID int64) (GithubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp, appID)
	var i GithubApp
	err := row.Scan(
		&i.AppID,
		&i.Slug,
		&i.PrivateKey,
		&i.ClientID,
		&i.ClientSecret,
		&i.UserToken,
		&i.RefreshToken,
		&i.UserTokenExpiresAt,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT since, etag FROM sync_cursors WHERE repository = ? AND endpoint = ?
`

type GetSyncCursorParams struct {
	Repository string
	Endpoint   string
}

type GetSyncCursorRow struct {
	Since sql.NullString
	Etag  sql.NullString
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (GetSyncCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.Repository, arg.Endpoint)
	var i GetSyncCursorRow
	err := row.Scan(&i.Since, &i.Etag)
	return i, err
}

const listDeviceLogins = `-- name: ListDeviceLogins :many
SELECT id, user_agent, created_at FROM device_logins ORDER BY id DESC
`

type ListDeviceLoginsRow struct {
	ID        int64
	UserAgent string
	CreatedAt string
}

func (q *Queries) ListDeviceLogins(ctx context.Context) ([]ListDeviceLoginsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceLogins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceLoginsRow
	for rows.Next() {
		var i ListDeviceLoginsRow
		if err := rows.Scan(&i.ID, &i.UserAgent, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events WHERE id > ? ORDER BY id
`

func (q *Queries) ListEventsAfter(ctx context.Context, id int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubApps = `-- name: ListGitHubApps :many
SELECT app_id, slug, private_key, client_id, client_secret, user_token, refresh_token, user_token_expires_at FROM github_apps ORDER BY app_id
`

func (q *Queries) ListGitHubApps(ctx context.Context) ([]GithubApp, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubApp
	for rows.Next() {
		var i GithubApp
		if err := rows.Scan(
			&i.AppID,
			&i.Slug,
			&i.PrivateKey,
			&i.ClientID,
			&i.ClientSecret,
			&i.UserToken,
			&i.RefreshToken,
			&i.UserTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestEvents = `-- name: ListLatestEvents :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListLatestEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listLatestEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkstreams = `-- name: ListWorkstreams :many
WITH activity AS (
    SELECT repository, workstream, dispatched_at AS time FROM tasks
    UNION ALL
    SELECT repository, workstream, started_at FROM sessions
    UNION ALL
    SELECT repository, workstream, time FROM chat_messages
    UNION ALL
    SELECT repository, workstream, time FROM lead_events
    UNION ALL
    SELECT repository, workstream, time FROM events
    UNION ALL
    SELECT repository, workstream, time FROM inbox_items
)
SELECT
    activity.repository,
    activity.workstream,
    CAST(MAX(activity.time) AS TEXT) AS last_activity,
    (SELECT COUNT(*) FROM tasks
     WHERE tasks.repository = activity.repository AND tasks.workstream = activity.workstream) AS tasks,
    (SELECT COUNT(*) FROM tasks
     WHERE tasks.repository = activity.repository AND tasks.workstream = activity.workstream
       AND tasks.state NOT IN ('ended', 'stopped')) AS open_tasks
FROM activity
WHERE activity.repository != '' AND activity.workstream != 0
GROUP BY activity.repository, activity.workstream
ORDER BY last_activity DESC
`

type ListWorkstreamsRow struct {
	Repository   string
	Workstream   int64
	LastActivity string
	Tasks        int64
	OpenTasks    int64
}

func (q *Queries) ListWorkstreams(ctx context.Context) ([]ListWorkstreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkstreamsRow
	for rows.Next() {
		var i ListWorkstreamsRow
		if err := rows.Scan(
			&i.Repository,
			&i.Workstream,
			&i.LastActivity,
			&i.Tasks,
			&i.OpenTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSyncCursor = `-- name: SetSyncCursor :exec
INSERT INTO sync_cursors (repository, endpoint, since, etag) VALUES (?, ?, ?, ?)
ON CONFLICT (repository, endpoint) DO UPDATE SET since = excluded.since, etag = excluded.etag
`

type SetSyncCursorParams struct {
	Repository string
	Endpoint   string
	Since      sql.NullString
	Etag       sql.NullString
}

func (q *Queries) SetSyncCursor(ctx context.Context, arg SetSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, setSyncCursor,
		arg.Repository,
		arg.Endpoint,
		arg.Since,
		arg.Etag,
	)
	return err
}

const setUserTokens = `-- name: SetUserTokens :exec
UPDATE github_apps SET user_token = ?, refresh_token = ?, user_token_expires_at = ?
WHERE app_id = ?
`

type SetUserTokensParams struct {
	UserToken          sql.NullString
	RefreshToken       sql.NullString
	UserTokenExpiresAt sql.NullString
	AppID              int64
}

func (q *Queries) SetUserTokens(ctx context.Context, arg SetUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, setUserTokens,
		arg.UserToken,
		arg.RefreshToken,
		arg.UserTokenExpiresAt,
		arg.AppID,
	)
	return err
}
