// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addChatMessage = `-- name: AddChatMessage :one
INSERT INTO chat_messages (organization, repository, workstream, author, time, text)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type AddChatMessageParams struct {
	Organization string
	Repository   string
	Workstream   int64
	Author       string
	Time         string
	Text         string
}

func (q *Queries) AddChatMessage(ctx context.Context, arg AddChatMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addChatMessage,
		arg.Organization,
		arg.Repository,
		arg.Workstream,
		arg.Author,
		arg.Time,
		arg.Text,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addCopiedBlocker = `-- name: AddCopiedBlocker :exec
INSERT INTO copied_blockers (repository, workstream, position, number, blocker_workstream, blocker_workstream_title)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddCopiedBlockerParams struct {
	Repository             string
	Workstream             int64
	Position               int64
	Number                 int64
	BlockerWorkstream      sql.NullInt64
	BlockerWorkstreamTitle sql.NullString
}

func (q *Queries) AddCopiedBlocker(ctx context.Context, arg AddCopiedBlockerParams) error {
	_, err := q.db.ExecContext(ctx, addCopiedBlocker,
		arg.Repository,
		arg.Workstream,
		arg.Position,
		arg.Number,
		arg.BlockerWorkstream,
		arg.BlockerWorkstreamTitle,
	)
	return err
}

const addCopiedIssue = `-- name: AddCopiedIssue :exec
INSERT INTO copied_issues (repository, workstream, position, number, parent, title, body, state, author, html_url, repository_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddCopiedIssueParams struct {
	Repository    string
	Workstream    int64
	Position      int64
	Number        int64
	Parent        int64
	Title         string
	Body          string
	State         string
	Author        string
	HtmlUrl       string
	RepositoryUrl string
}

func (q *Queries) AddCopiedIssue(ctx context.Context, arg AddCopiedIssueParams) error {
	_, err := q.db.ExecContext(ctx, addCopiedIssue,
		arg.Repository,
		arg.Workstream,
		arg.Position,
		arg.Number,
		arg.Parent,
		arg.Title,
		arg.Body,
		arg.State,
		arg.Author,
		arg.HtmlUrl,
		arg.RepositoryUrl,
	)
	return err
}

const addCopiedIssueLabel = `-- name: AddCopiedIssueLabel :exec
INSERT INTO copied_issue_labels (repository, workstream, position, name) VALUES (?, ?, ?, ?)
`

type AddCopiedIssueLabelParams struct {
	Repository string
	Workstream int64
	Position   int64
	Name       string
}

func (q *Queries) AddCopiedIssueLabel(ctx context.Context, arg AddCopiedIssueLabelParams) error {
	_, err := q.db.ExecContext(ctx, addCopiedIssueLabel,
		arg.Repository,
		arg.Workstream,
		arg.Position,
		arg.Name,
	)
	return err
}

const addCopiedWorkstream = `-- name: AddCopiedWorkstream :exec
INSERT INTO copied_workstreams (repository, number, title, body, autopilot)
VALUES (?1, ?2, ?3, ?4, CAST(?5 AS BOOLEAN))
ON CONFLICT (repository, number) DO NOTHING
`

type AddCopiedWorkstreamParams struct {
	Repository string
	Number     int64
	Title      string
	Body       string
	Autopilot  bool
}

// The Lead tool create_workstream and the poll can both add a new Workstream.
func (q *Queries) AddCopiedWorkstream(ctx context.Context, arg AddCopiedWorkstreamParams) error {
	_, err := q.db.ExecContext(ctx, addCopiedWorkstream,
		arg.Repository,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.Autopilot,
	)
	return err
}

const addDeviceLogin = `-- name: AddDeviceLogin :exec
INSERT INTO device_logins (token_hash, password_fingerprint, user_agent, created_at)
VALUES (?, ?, ?, ?)
`

type AddDeviceLoginParams struct {
	TokenHash           []byte
	PasswordFingerprint []byte
	UserAgent           string
	CreatedAt           string
}

func (q *Queries) AddDeviceLogin(ctx context.Context, arg AddDeviceLoginParams) error {
	_, err := q.db.ExecContext(ctx, addDeviceLogin,
		arg.TokenHash,
		arg.PasswordFingerprint,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const addEvent = `-- name: AddEvent :exec
INSERT INTO events (time, repository, workstream, issue, actor, text, link) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddEventParams struct {
	Time       string
	Repository string
	Workstream int64
	Issue      int64
	Actor      string
	Text       string
	Link       string
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) error {
	_, err := q.db.ExecContext(ctx, addEvent,
		arg.Time,
		arg.Repository,
		arg.Workstream,
		arg.Issue,
		arg.Actor,
		arg.Text,
		arg.Link,
	)
	return err
}

const addGitHubApp = `-- name: AddGitHubApp :exec
INSERT INTO github_apps (app_id, slug, private_key, client_id, client_secret)
VALUES (?, ?, ?, ?, ?)
`

type AddGitHubAppParams struct {
	AppID        int64
	Slug         string
	PrivateKey   string
	ClientID     string
	ClientSecret string
}

func (q *Queries) AddGitHubApp(ctx context.Context, arg AddGitHubAppParams) error {
	_, err := q.db.ExecContext(ctx, addGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.PrivateKey,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const addInboxItem = `-- name: AddInboxItem :one
INSERT INTO inbox_items (kind, organization, repository, workstream, issue, text, link, time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, kind, repository, workstream, issue, text, link, time, dismissed_at, organization
`

type AddInboxItemParams struct {
	Kind         string
	Organization string
	Repository   string
	Workstream   int64
	Issue        int64
	Text         string
	Link         string
	Time         string
}

func (q *Queries) AddInboxItem(ctx context.Context, arg AddInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, addInboxItem,
		arg.Kind,
		arg.Organization,
		arg.Repository,
		arg.Workstream,
		arg.Issue,
		arg.Text,
		arg.Link,
		arg.Time,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Repository,
		&i.Workstream,
		&i.Issue,
		&i.Text,
		&i.Link,
		&i.Time,
		&i.DismissedAt,
		&i.Organization,
	)
	return i, err
}

const addLeadEvent = `-- name: AddLeadEvent :exec
INSERT INTO lead_events (repository, workstream, issue, kind, payload, time, chat_message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddLeadEventParams struct {
	Repository  string
	Workstream  int64
	Issue       sql.NullInt64
	Kind        string
	Payload     string
	Time        string
	ChatMessage sql.NullInt64
}

func (q *Queries) AddLeadEvent(ctx context.Context, arg AddLeadEventParams) error {
	_, err := q.db.ExecContext(ctx, addLeadEvent,
		arg.Repository,
		arg.Workstream,
		arg.Issue,
		arg.Kind,
		arg.Payload,
		arg.Time,
		arg.ChatMessage,
	)
	return err
}

const addSession = `-- name: AddSession :one
INSERT INTO sessions (role, harness, model, organization, repository, workstream, issue, parent, started_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent
`

type AddSessionParams struct {
	Role         string
	Harness      string
	Model        string
	Organization string
	Repository   string
	Workstream   int64
	Issue        sql.NullInt64
	Parent       sql.NullInt64
	StartedAt    string
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, addSession,
		arg.Role,
		arg.Harness,
		arg.Model,
		arg.Organization,
		arg.Repository,
		arg.Workstream,
		arg.Issue,
		arg.Parent,
		arg.StartedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Harness,
		&i.Model,
		&i.Repository,
		&i.Workstream,
		&i.AcpSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.QueueReason,
		&i.Organization,
		&i.Issue,
		&i.Parent,
	)
	return i, err
}

const addTranscriptRow = `-- name: AddTranscriptRow :one
INSERT INTO transcript (session, time, kind, json) VALUES (?, ?, ?, ?)
RETURNING id, session, time, kind, json
`

type AddTranscriptRowParams struct {
	Session int64
	Time    string
	Kind    string
	Json    string
}

func (q *Queries) AddTranscriptRow(ctx context.Context, arg AddTranscriptRowParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, addTranscriptRow,
		arg.Session,
		arg.Time,
		arg.Kind,
		arg.Json,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Time,
		&i.Kind,
		&i.Json,
	)
	return i, err
}

const addWorkerRestart = `-- name: AddWorkerRestart :one
UPDATE tasks SET worker_restarts = worker_restarts + 1 WHERE id = ?1 AND worker_restarts < ?2
RETURNING worker_restarts
`

type AddWorkerRestartParams struct {
	ID  int64
	Max int64
}

func (q *Queries) AddWorkerRestart(ctx context.Context, arg AddWorkerRestartParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addWorkerRestart, arg.ID, arg.Max)
	var worker_restarts int64
	err := row.Scan(&worker_restarts)
	return worker_restarts, err
}

const clearQueueReason = `-- name: ClearQueueReason :one
UPDATE sessions SET queue_reason = NULL WHERE id = ?
RETURNING id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent
`

func (q *Queries) ClearQueueReason(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, clearQueueReason, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Harness,
		&i.Model,
		&i.Repository,
		&i.Workstream,
		&i.AcpSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.QueueReason,
		&i.Organization,
		&i.Issue,
		&i.Parent,
	)
	return i, err
}

const deleteCopiedBlocker = `-- name: DeleteCopiedBlocker :execrows
DELETE FROM copied_blockers WHERE repository = ? AND number = ?
`

type DeleteCopiedBlockerParams struct {
	Repository string
	Number     int64
}

func (q *Queries) DeleteCopiedBlocker(ctx context.Context, arg DeleteCopiedBlockerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCopiedBlocker, arg.Repository, arg.Number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCopiedBlockers = `-- name: DeleteCopiedBlockers :exec
DELETE FROM copied_blockers WHERE repository = ? AND workstream = ?
`

type DeleteCopiedBlockersParams struct {
	Repository string
	Workstream int64
}

func (q *Queries) DeleteCopiedBlockers(ctx context.Context, arg DeleteCopiedBlockersParams) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedBlockers, arg.Repository, arg.Workstream)
	return err
}

const deleteCopiedBlockersOf = `-- name: DeleteCopiedBlockersOf :exec
DELETE FROM copied_blockers WHERE repository = ?
`

func (q *Queries) DeleteCopiedBlockersOf(ctx context.Context, repository string) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedBlockersOf, repository)
	return err
}

const deleteCopiedIssueLabels = `-- name: DeleteCopiedIssueLabels :exec
DELETE FROM copied_issue_labels WHERE repository = ? AND workstream = ?
`

type DeleteCopiedIssueLabelsParams struct {
	Repository string
	Workstream int64
}

func (q *Queries) DeleteCopiedIssueLabels(ctx context.Context, arg DeleteCopiedIssueLabelsParams) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedIssueLabels, arg.Repository, arg.Workstream)
	return err
}

const deleteCopiedIssueLabelsAt = `-- name: DeleteCopiedIssueLabelsAt :exec
DELETE FROM copied_issue_labels WHERE repository = ? AND workstream = ? AND position = ?
`

type DeleteCopiedIssueLabelsAtParams struct {
	Repository string
	Workstream int64
	Position   int64
}

func (q *Queries) DeleteCopiedIssueLabelsAt(ctx context.Context, arg DeleteCopiedIssueLabelsAtParams) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedIssueLabelsAt, arg.Repository, arg.Workstream, arg.Position)
	return err
}

const deleteCopiedIssueLabelsOf = `-- name: DeleteCopiedIssueLabelsOf :exec
DELETE FROM copied_issue_labels WHERE repository = ?
`

func (q *Queries) DeleteCopiedIssueLabelsOf(ctx context.Context, repository string) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedIssueLabelsOf, repository)
	return err
}

const deleteCopiedIssues = `-- name: DeleteCopiedIssues :exec
DELETE FROM copied_issues WHERE repository = ? AND workstream = ?
`

type DeleteCopiedIssuesParams struct {
	Repository string
	Workstream int64
}

func (q *Queries) DeleteCopiedIssues(ctx context.Context, arg DeleteCopiedIssuesParams) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedIssues, arg.Repository, arg.Workstream)
	return err
}

const deleteCopiedIssuesOf = `-- name: DeleteCopiedIssuesOf :exec
DELETE FROM copied_issues WHERE repository = ?
`

func (q *Queries) DeleteCopiedIssuesOf(ctx context.Context, repository string) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedIssuesOf, repository)
	return err
}

const deleteCopiedWorkstream = `-- name: DeleteCopiedWorkstream :exec
DELETE FROM copied_workstreams WHERE repository = ? AND number = ?
`

type DeleteCopiedWorkstreamParams struct {
	Repository string
	Number     int64
}

func (q *Queries) DeleteCopiedWorkstream(ctx context.Context, arg DeleteCopiedWorkstreamParams) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedWorkstream, arg.Repository, arg.Number)
	return err
}

const deleteCopiedWorkstreamsOf = `-- name: DeleteCopiedWorkstreamsOf :exec
DELETE FROM copied_workstreams WHERE repository = ?
`

func (q *Queries) DeleteCopiedWorkstreamsOf(ctx context.Context, repository string) error {
	_, err := q.db.ExecContext(ctx, deleteCopiedWorkstreamsOf, repository)
	return err
}

const deleteDeviceLogin = `-- name: DeleteDeviceLogin :exec
DELETE FROM device_logins WHERE id = ?
`

func (q *Queries) DeleteDeviceLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceLogin, id)
	return err
}

const deleteHarnessPause = `-- name: DeleteHarnessPause :exec
DELETE FROM harness_pauses WHERE harness = ?
`

func (q *Queries) DeleteHarnessPause(ctx context.Context, harness string) error {
	_, err := q.db.ExecContext(ctx, deleteHarnessPause, harness)
	return err
}

const deleteOtherPasswordLogins = `-- name: DeleteOtherPasswordLogins :exec
DELETE FROM device_logins WHERE password_fingerprint != ?
`

func (q *Queries) DeleteOtherPasswordLogins(ctx context.Context, passwordFingerprint []byte) error {
	_, err := q.db.ExecContext(ctx, deleteOtherPasswordLogins, passwordFingerprint)
	return err
}

const deliverLeadEvents = `-- name: DeliverLeadEvents :exec
UPDATE lead_events SET delivered_at = ? WHERE repository = ? AND workstream = ? AND delivered_at IS NULL
`

type DeliverLeadEventsParams struct {
	DeliveredAt sql.NullString
	Repository  string
	Workstream  int64
}

func (q *Queries) DeliverLeadEvents(ctx context.Context, arg DeliverLeadEventsParams) error {
	_, err := q.db.ExecContext(ctx, deliverLeadEvents, arg.DeliveredAt, arg.Repository, arg.Workstream)
	return err
}

const dismissInboxItem = `-- name: DismissInboxItem :exec
UPDATE inbox_items SET dismissed_at = ? WHERE id = ?
`

type DismissInboxItemParams struct {
	DismissedAt sql.NullString
	ID          int64
}

func (q *Queries) DismissInboxItem(ctx context.Context, arg DismissInboxItemParams) error {
	_, err := q.db.ExecContext(ctx, dismissInboxItem, arg.DismissedAt, arg.ID)
	return err
}

const endSession = `-- name: EndSession :one
UPDATE sessions SET ended_at = ?, end_reason = ?, queue_reason = NULL WHERE id = ?
RETURNING id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent
`

type EndSessionParams struct {
	EndedAt   sql.NullString
	EndReason sql.NullString
	ID        int64
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, endSession, arg.EndedAt, arg.EndReason, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Harness,
		&i.Model,
		&i.Repository,
		&i.Workstream,
		&i.AcpSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.QueueReason,
		&i.Organization,
		&i.Issue,
		&i.Parent,
	)
	return i, err
}

const endTask = `-- name: EndTask :exec
UPDATE tasks SET state = 'ended' WHERE id = ?
`

func (q *Queries) EndTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, endTask, id)
	return err
}

const findDeviceLogin = `-- name: FindDeviceLogin :one
SELECT id FROM device_logins WHERE token_hash = ?
`

func (q *Queries) FindDeviceLogin(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, findDeviceLogin, tokenHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCopiedIssueWorkstream = `-- name: GetCopiedIssueWorkstream :one
SELECT workstream FROM copied_issues WHERE repository = ? AND number = ? AND repository_url = ? LIMIT 1
`

type GetCopiedIssueWorkstreamParams struct {
	Repository    string
	Number        int64
	RepositoryUrl string
}

// A row of another repository can have the number of an issue of this repository, so the repository URL must match.
func (q *Queries) GetCopiedIssueWorkstream(ctx context.Context, arg GetCopiedIssueWorkstreamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCopiedIssueWorkstream, arg.Repository, arg.Number, arg.RepositoryUrl)
	var workstream int64
	err := row.Scan(&workstream)
	return workstream, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT app_id, slug, private_key, client_id, client_secret, user_token, refresh_token, user_token_expires_at FROM github_apps WHERE app_id = ?
`

func (q *Queries) GetGitHubApp(ctx context.Context, appID int64) (GithubApp, error) {
	row := q.db.QueryRowContext(ctx, getGitHubApp, appID)
	var i GithubApp
	err := row.Scan(
		&i.AppID,
		&i.Slug,
		&i.PrivateKey,
		&i.ClientID,
		&i.ClientSecret,
		&i.UserToken,
		&i.RefreshToken,
		&i.UserTokenExpiresAt,
	)
	return i, err
}

const getHarnessPause = `-- name: GetHarnessPause :one
SELECT harness, paused_until, inbox_item FROM harness_pauses WHERE harness = ?
`

func (q *Queries) GetHarnessPause(ctx context.Context, harness string) (HarnessPause, error) {
	row := q.db.QueryRowContext(ctx, getHarnessPause, harness)
	var i HarnessPause
	err := row.Scan(&i.Harness, &i.PausedUntil, &i.InboxItem)
	return i, err
}

const getLiveTask = `-- name: GetLiveTask :one
SELECT id, repository, issue, workstream, state, dispatched_at, branch, queued_at, fix_rounds, pull_request, judged_at, worker_restarts, worker, worker_input, review_rounds, review_comment, check_head FROM tasks WHERE repository = ? AND issue = ? AND state <> 'ended'
`

type GetLiveTaskParams struct {
	Repository string
	Issue      int64
}

func (q *Queries) GetLiveTask(ctx context.Context, arg GetLiveTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getLiveTask, arg.Repository, arg.Issue)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Issue,
		&i.Workstream,
		&i.State,
		&i.DispatchedAt,
		&i.Branch,
		&i.QueuedAt,
		&i.FixRounds,
		&i.PullRequest,
		&i.JudgedAt,
		&i.WorkerRestarts,
		&i.Worker,
		&i.WorkerInput,
		&i.ReviewRounds,
		&i.ReviewComment,
		&i.CheckHead,
	)
	return i, err
}

const getLiveTaskByPullRequest = `-- name: GetLiveTaskByPullRequest :one
SELECT id, repository, issue, workstream, state, dispatched_at, branch, queued_at, fix_rounds, pull_request, judged_at, worker_restarts, worker, worker_input, review_rounds, review_comment, check_head FROM tasks WHERE repository = ? AND pull_request = ? AND state <> 'ended'
`

type GetLiveTaskByPullRequestParams struct {
	Repository  string
	PullRequest sql.NullInt64
}

func (q *Queries) GetLiveTaskByPullRequest(ctx context.Context, arg GetLiveTaskByPullRequestParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getLiveTaskByPullRequest, arg.Repository, arg.PullRequest)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Issue,
		&i.Workstream,
		&i.State,
		&i.DispatchedAt,
		&i.Branch,
		&i.QueuedAt,
		&i.FixRounds,
		&i.PullRequest,
		&i.JudgedAt,
		&i.WorkerRestarts,
		&i.Worker,
		&i.WorkerInput,
		&i.ReviewRounds,
		&i.ReviewComment,
		&i.CheckHead,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT since, etag FROM sync_cursors WHERE repository = ? AND endpoint = ?
`

type GetSyncCursorParams struct {
	Repository string
	Endpoint   string
}

type GetSyncCursorRow struct {
	Since sql.NullString
	Etag  sql.NullString
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (GetSyncCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.Repository, arg.Endpoint)
	var i GetSyncCursorRow
	err := row.Scan(&i.Since, &i.Etag)
	return i, err
}

const hasCopiedWorkstream = `-- name: HasCopiedWorkstream :one
SELECT EXISTS (SELECT 1 FROM copied_workstreams WHERE repository = ? AND number = ?)
`

type HasCopiedWorkstreamParams struct {
	Repository string
	Number     int64
}

func (q *Queries) HasCopiedWorkstream(ctx context.Context, arg HasCopiedWorkstreamParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCopiedWorkstream, arg.Repository, arg.Number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCopiedIssueLabels = `-- name: ListCopiedIssueLabels :many
SELECT name FROM copied_issue_labels WHERE repository = ? AND workstream = ? AND position = ? ORDER BY name
`

type ListCopiedIssueLabelsParams struct {
	Repository string
	Workstream int64
	Position   int64
}

func (q *Queries) ListCopiedIssueLabels(ctx context.Context, arg ListCopiedIssueLabelsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedIssueLabels, arg.Repository, arg.Workstream, arg.Position)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedIssueRows = `-- name: ListCopiedIssueRows :many
SELECT repository, workstream, position FROM copied_issues WHERE number = ? AND repository_url = ?
`

type ListCopiedIssueRowsParams struct {
	Number        int64
	RepositoryUrl string
}

type ListCopiedIssueRowsRow struct {
	Repository string
	Workstream int64
	Position   int64
}

func (q *Queries) ListCopiedIssueRows(ctx context.Context, arg ListCopiedIssueRowsParams) ([]ListCopiedIssueRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedIssueRows, arg.Number, arg.RepositoryUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCopiedIssueRowsRow
	for rows.Next() {
		var i ListCopiedIssueRowsRow
		if err := rows.Scan(&i.Repository, &i.Workstream, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedRepositories = `-- name: ListCopiedRepositories :many
SELECT DISTINCT repository FROM copied_workstreams
`

func (q *Queries) ListCopiedRepositories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var repository string
		if err := rows.Scan(&repository); err != nil {
			return nil, err
		}
		items = append(items, repository)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedWorkstreams = `-- name: ListCopiedWorkstreams :many
SELECT w.repository, w.number, w.title, w.body, CAST(w.autopilot AS BOOLEAN) AS autopilot,
       CAST(EXISTS (SELECT 1 FROM copied_issues i
               WHERE i.repository = w.repository AND i.workstream = w.number AND i.parent = w.number)
       AND NOT EXISTS (SELECT 1 FROM copied_issues i
                       WHERE i.repository = w.repository AND i.workstream = w.number AND i.parent = w.number
                         AND i.state != 'closed') AS BOOLEAN) AS all_tasks_closed
FROM copied_workstreams w
ORDER BY w.repository, w.number DESC
`

type ListCopiedWorkstreamsRow struct {
	Repository     string
	Number         int64
	Title          string
	Body           string
	Autopilot      bool
	AllTasksClosed bool
}

func (q *Queries) ListCopiedWorkstreams(ctx context.Context) ([]ListCopiedWorkstreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedWorkstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCopiedWorkstreamsRow
	for rows.Next() {
		var i ListCopiedWorkstreamsRow
		if err := rows.Scan(
			&i.Repository,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.Autopilot,
			&i.AllTasksClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedWorkstreamsWithBlocker = `-- name: ListCopiedWorkstreamsWithBlocker :many
SELECT DISTINCT workstream FROM copied_blockers WHERE repository = ? AND number = ?
`

type ListCopiedWorkstreamsWithBlockerParams struct {
	Repository string
	Number     int64
}

func (q *Queries) ListCopiedWorkstreamsWithBlocker(ctx context.Context, arg ListCopiedWorkstreamsWithBlockerParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedWorkstreamsWithBlocker, arg.Repository, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var workstream int64
		if err := rows.Scan(&workstream); err != nil {
			return nil, err
		}
		items = append(items, workstream)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedWorkstreamsWithBlockerIn = `-- name: ListCopiedWorkstreamsWithBlockerIn :many
SELECT DISTINCT workstream FROM copied_blockers WHERE repository = ? AND blocker_workstream = ?
`

type ListCopiedWorkstreamsWithBlockerInParams struct {
	Repository        string
	BlockerWorkstream sql.NullInt64
}

func (q *Queries) ListCopiedWorkstreamsWithBlockerIn(ctx context.Context, arg ListCopiedWorkstreamsWithBlockerInParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedWorkstreamsWithBlockerIn, arg.Repository, arg.BlockerWorkstream)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var workstream int64
		if err := rows.Scan(&workstream); err != nil {
			return nil, err
		}
		items = append(items, workstream)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopiedWorkstreamsWithLabelChange = `-- name: ListCopiedWorkstreamsWithLabelChange :many
SELECT i.workstream FROM copied_issues i
WHERE i.repository = ?1 AND i.number = ?2 AND i.repository_url = ?3
  AND EXISTS (
      SELECT 1 FROM copied_issue_labels l
      WHERE l.repository = i.repository AND l.workstream = i.workstream AND l.position = i.position AND l.name = ?4
  ) != CAST(?5 AS BOOLEAN)
`

type ListCopiedWorkstreamsWithLabelChangeParams struct {
	Repository    string
	Number        int64
	RepositoryUrl string
	Name          string
	Present       bool
}

func (q *Queries) ListCopiedWorkstreamsWithLabelChange(ctx context.Context, arg ListCopiedWorkstreamsWithLabelChangeParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCopiedWorkstreamsWithLabelChange,
		arg.Repository,
		arg.Number,
		arg.RepositoryUrl,
		arg.Name,
		arg.Present,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var workstream int64
		if err := rows.Scan(&workstream); err != nil {
			return nil, err
		}
		items = append(items, workstream)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceLogins = `-- name: ListDeviceLogins :many
SELECT id, user_agent, created_at FROM device_logins ORDER BY id DESC
`

type ListDeviceLoginsRow struct {
	ID        int64
	UserAgent string
	CreatedAt string
}

func (q *Queries) ListDeviceLogins(ctx context.Context) ([]ListDeviceLoginsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceLogins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceLoginsRow
	for rows.Next() {
		var i ListDeviceLoginsRow
		if err := rows.Scan(&i.ID, &i.UserAgent, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events WHERE id > ? ORDER BY id
`

func (q *Queries) ListEventsAfter(ctx context.Context, id int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubApps = `-- name: ListGitHubApps :many
SELECT app_id, slug, private_key, client_id, client_secret, user_token, refresh_token, user_token_expires_at FROM github_apps ORDER BY app_id
`

func (q *Queries) ListGitHubApps(ctx context.Context) ([]GithubApp, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubApp
	for rows.Next() {
		var i GithubApp
		if err := rows.Scan(
			&i.AppID,
			&i.Slug,
			&i.PrivateKey,
			&i.ClientID,
			&i.ClientSecret,
			&i.UserToken,
			&i.RefreshToken,
			&i.UserTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHarnessPauses = `-- name: ListHarnessPauses :many
SELECT harness, paused_until, inbox_item FROM harness_pauses ORDER BY harness
`

func (q *Queries) ListHarnessPauses(ctx context.Context) ([]HarnessPause, error) {
	rows, err := q.db.QueryContext(ctx, listHarnessPauses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HarnessPause
	for rows.Next() {
		var i HarnessPause
		if err := rows.Scan(&i.Harness, &i.PausedUntil, &i.InboxItem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestEvents = `-- name: ListLatestEvents :many
SELECT id, time, repository, workstream, issue, actor, text, link FROM events ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListLatestEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listLatestEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Repository,
			&i.Workstream,
			&i.Issue,
			&i.Actor,
			&i.Text,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveTasks = `-- name: ListLiveTasks :many
SELECT id, repository, issue, workstream, state, dispatched_at, branch, queued_at, fix_rounds, pull_request, judged_at, worker_restarts, worker, worker_input, review_rounds, review_comment, check_head FROM tasks WHERE repository = ? AND state <> 'ended' ORDER BY id
`

func (q *Queries) ListLiveTasks(ctx context.Context, repository string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listLiveTasks, repository)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.Issue,
			&i.Workstream,
			&i.State,
			&i.DispatchedAt,
			&i.Branch,
			&i.QueuedAt,
			&i.FixRounds,
			&i.PullRequest,
			&i.JudgedAt,
			&i.WorkerRestarts,
			&i.Worker,
			&i.WorkerInput,
			&i.ReviewRounds,
			&i.ReviewComment,
			&i.CheckHead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSessionIDs = `-- name: ListOpenSessionIDs :many
SELECT id FROM sessions WHERE ended_at IS NULL ORDER BY id
`

func (q *Queries) ListOpenSessionIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOpenSessionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSessions = `-- name: ListOpenSessions :many
SELECT sessions.id, sessions.role, sessions.harness, sessions.model, sessions.repository, sessions.workstream, sessions.acp_session_id, sessions.started_at, sessions.ended_at, sessions.end_reason, sessions.queue_reason, sessions.organization, sessions.issue, sessions.parent, w.title AS workstream_title, i.title AS issue_title,
       (SELECT t.pull_request FROM tasks t
        WHERE t.repository = sessions.repository AND t.issue = sessions.issue
        ORDER BY t.id DESC LIMIT 1) AS pull_request
FROM sessions
LEFT JOIN copied_workstreams w ON w.repository = sessions.repository AND w.number = sessions.workstream
LEFT JOIN copied_issues i
  ON i.repository = sessions.repository AND i.workstream = sessions.workstream AND i.number = sessions.issue
WHERE sessions.ended_at IS NULL ORDER BY sessions.id
`

type ListOpenSessionsRow struct {
	Session         Session
	WorkstreamTitle sql.NullString
	IssueTitle      sql.NullString
	PullRequest     sql.NullInt64
}

func (q *Queries) ListOpenSessions(ctx context.Context) ([]ListOpenSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenSessionsRow
	for rows.Next() {
		var i ListOpenSessionsRow
		if err := rows.Scan(
			&i.Session.ID,
			&i.Session.Role,
			&i.Session.Harness,
			&i.Session.Model,
			&i.Session.Repository,
			&i.Session.Workstream,
			&i.Session.AcpSessionID,
			&i.Session.StartedAt,
			&i.Session.EndedAt,
			&i.Session.EndReason,
			&i.Session.QueueReason,
			&i.Session.Organization,
			&i.Session.Issue,
			&i.Session.Parent,
			&i.WorkstreamTitle,
			&i.IssueTitle,
			&i.PullRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedTasks = `-- name: ListQueuedTasks :many
SELECT id, queued_at FROM tasks WHERE state = 'queued' ORDER BY queued_at, id
`

type ListQueuedTasksRow struct {
	ID       int64
	QueuedAt sql.NullString
}

func (q *Queries) ListQueuedTasks(ctx context.Context) ([]ListQueuedTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueuedTasksRow
	for rows.Next() {
		var i ListQueuedTasksRow
		if err := rows.Scan(&i.ID, &i.QueuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent FROM sessions WHERE organization = ? AND repository = ? AND workstream = ? ORDER BY id
`

type ListSessionsParams struct {
	Organization string
	Repository   string
	Workstream   int64
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Organization, arg.Repository, arg.Workstream)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Harness,
			&i.Model,
			&i.Repository,
			&i.Workstream,
			&i.AcpSessionID,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.QueueReason,
			&i.Organization,
			&i.Issue,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskPullRequests = `-- name: ListTaskPullRequests :many
SELECT CAST(pull_request AS INTEGER) FROM tasks WHERE repository = ? AND workstream = ? AND pull_request IS NOT NULL ORDER BY id
`

type ListTaskPullRequestsParams struct {
	Repository string
	Workstream int64
}

func (q *Queries) ListTaskPullRequests(ctx context.Context, arg ListTaskPullRequestsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTaskPullRequests, arg.Repository, arg.Workstream)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var pull_request int64
		if err := rows.Scan(&pull_request); err != nil {
			return nil, err
		}
		items = append(items, pull_request)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscript = `-- name: ListTranscript :many
SELECT id, session, time, kind, json FROM transcript WHERE session = ? ORDER BY id
`

func (q *Queries) ListTranscript(ctx context.Context, session int64) ([]Transcript, error) {
	rows, err := q.db.QueryContext(ctx, listTranscript, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcript
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.Time,
			&i.Kind,
			&i.Json,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setACPSessionID = `-- name: SetACPSessionID :exec
UPDATE sessions SET acp_session_id = ? WHERE id = ?
`

type SetACPSessionIDParams struct {
	AcpSessionID sql.NullString
	ID           int64
}

func (q *Queries) SetACPSessionID(ctx context.Context, arg SetACPSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, setACPSessionID, arg.AcpSessionID, arg.ID)
	return err
}

const setCopiedAutopilot = `-- name: SetCopiedAutopilot :exec
UPDATE copied_workstreams SET autopilot = CAST(?1 AS BOOLEAN)
WHERE repository = ?2 AND number = ?3
`

type SetCopiedAutopilotParams struct {
	Autopilot  bool
	Repository string
	Number     int64
}

func (q *Queries) SetCopiedAutopilot(ctx context.Context, arg SetCopiedAutopilotParams) error {
	_, err := q.db.ExecContext(ctx, setCopiedAutopilot, arg.Autopilot, arg.Repository, arg.Number)
	return err
}

const setHarnessPause = `-- name: SetHarnessPause :exec
INSERT INTO harness_pauses (harness, paused_until, inbox_item) VALUES (?, ?, ?)
ON CONFLICT (harness) DO UPDATE SET paused_until = excluded.paused_until, inbox_item = excluded.inbox_item
`

type SetHarnessPauseParams struct {
	Harness     string
	PausedUntil string
	InboxItem   int64
}

func (q *Queries) SetHarnessPause(ctx context.Context, arg SetHarnessPauseParams) error {
	_, err := q.db.ExecContext(ctx, setHarnessPause, arg.Harness, arg.PausedUntil, arg.InboxItem)
	return err
}

const setQueueReason = `-- name: SetQueueReason :one
UPDATE sessions SET queue_reason = ? WHERE id = ?
RETURNING id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent
`

type SetQueueReasonParams struct {
	QueueReason sql.NullString
	ID          int64
}

func (q *Queries) SetQueueReason(ctx context.Context, arg SetQueueReasonParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, setQueueReason, arg.QueueReason, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Harness,
		&i.Model,
		&i.Repository,
		&i.Workstream,
		&i.AcpSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.QueueReason,
		&i.Organization,
		&i.Issue,
		&i.Parent,
	)
	return i, err
}

const setSyncCursor = `-- name: SetSyncCursor :exec
INSERT INTO sync_cursors (repository, endpoint, since, etag) VALUES (?, ?, ?, ?)
ON CONFLICT (repository, endpoint) DO UPDATE SET since = excluded.since, etag = excluded.etag
`

type SetSyncCursorParams struct {
	Repository string
	Endpoint   string
	Since      sql.NullString
	Etag       sql.NullString
}

func (q *Queries) SetSyncCursor(ctx context.Context, arg SetSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, setSyncCursor,
		arg.Repository,
		arg.Endpoint,
		arg.Since,
		arg.Etag,
	)
	return err
}

const setTaskState = `-- name: SetTaskState :execrows
UPDATE tasks SET state = ?1 WHERE id = ?2 AND state = ?3
`

type SetTaskStateParams struct {
	State     string
	ID        int64
	FromState string
}

func (q *Queries) SetTaskState(ctx context.Context, arg SetTaskStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskState, arg.State, arg.ID, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTranscriptJSON = `-- name: SetTranscriptJSON :one
UPDATE transcript SET json = ? WHERE id = ?
RETURNING id, session, time, kind, json
`

type SetTranscriptJSONParams struct {
	Json string
	ID   int64
}

func (q *Queries) SetTranscriptJSON(ctx context.Context, arg SetTranscriptJSONParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, setTranscriptJSON, arg.Json, arg.ID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Time,
		&i.Kind,
		&i.Json,
	)
	return i, err
}

const setUserTokens = `-- name: SetUserTokens :exec
UPDATE github_apps SET user_token = ?, refresh_token = ?, user_token_expires_at = ?
WHERE app_id = ?
`

type SetUserTokensParams struct {
	UserToken          sql.NullString
	RefreshToken       sql.NullString
	UserTokenExpiresAt sql.NullString
	AppID              int64
}

func (q *Queries) SetUserTokens(ctx context.Context, arg SetUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, setUserTokens,
		arg.UserToken,
		arg.RefreshToken,
		arg.UserTokenExpiresAt,
		arg.AppID,
	)
	return err
}

const startSession = `-- name: StartSession :one
UPDATE sessions SET started_at = ?, queue_reason = NULL WHERE id = ?
RETURNING id, role, harness, model, repository, workstream, acp_session_id, started_at, ended_at, end_reason, queue_reason, organization, issue, parent
`

type StartSessionParams struct {
	StartedAt string
	ID        int64
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, startSession, arg.StartedAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Harness,
		&i.Model,
		&i.Repository,
		&i.Workstream,
		&i.AcpSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.QueueReason,
		&i.Organization,
		&i.Issue,
		&i.Parent,
	)
	return i, err
}

const updateCopiedBlockerTitles = `-- name: UpdateCopiedBlockerTitles :execrows
UPDATE copied_blockers SET blocker_workstream_title = ?1
WHERE repository = ?2 AND blocker_workstream = ?3
  AND blocker_workstream_title IS NOT ?1
`

type UpdateCopiedBlockerTitlesParams struct {
	Title      sql.NullString
	Repository string
	Workstream sql.NullInt64
}

func (q *Queries) UpdateCopiedBlockerTitles(ctx context.Context, arg UpdateCopiedBlockerTitlesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCopiedBlockerTitles, arg.Title, arg.Repository, arg.Workstream)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCopiedIssue = `-- name: UpdateCopiedIssue :execrows
UPDATE copied_issues SET title = ?1, body = ?2, state = ?3, author = ?4
WHERE number = ?5 AND repository_url = ?6
  AND (title != ?1 OR body != ?2 OR state != ?3 OR author != ?4)
`

type UpdateCopiedIssueParams struct {
	Title         string
	Body          string
	State         string
	Author        string
	Number        int64
	RepositoryUrl string
}

// A tree can hold an issue of another repository as a leaf, so the change goes to the rows of all repositories.
func (q *Queries) UpdateCopiedIssue(ctx context.Context, arg UpdateCopiedIssueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCopiedIssue,
		arg.Title,
		arg.Body,
		arg.State,
		arg.Author,
		arg.Number,
		arg.RepositoryUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCopiedWorkstream = `-- name: UpdateCopiedWorkstream :execrows
UPDATE copied_workstreams SET title = ?1, body = ?2, autopilot = CAST(?3 AS BOOLEAN)
WHERE repository = ?4 AND number = ?5
  AND (title != ?1 OR body != ?2 OR autopilot != CAST(?3 AS BOOLEAN))
`

type UpdateCopiedWorkstreamParams struct {
	Title      string
	Body       string
	Autopilot  bool
	Repository string
	Number     int64
}

func (q *Queries) UpdateCopiedWorkstream(ctx context.Context, arg UpdateCopiedWorkstreamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCopiedWorkstream,
		arg.Title,
		arg.Body,
		arg.Autopilot,
		arg.Repository,
		arg.Number,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
